language: ruby
rvm:
  - 2.3
script:
  - gem install html-proofer && bundle exec jekyll build && bundle exec htmlproofer ./_site --only-4xx --disable-external
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
